### ISSUE TITLE
Unable to find a specification for `PointFree-Validated (~> 0.1)`

### ISSUE THREAD

**Issue by YoungCarmen** [pointfreeco/swift-validated#2]
use CocoaPods to install 
target 'TagDemo' do
    pod 'PointFree-Validated', '~> 0.1'
end
error happens  
Unable to find a specification for `PointFree-Validated (~> 0.1)`

**Comment by stephencelis** [comment]
Thanks for the report! Can you try running `pod repo update` before `pod install`? Validated was just pushed recently so your local pod repo may be out of date.

**Comment by stephencelis** [comment]
@YoungCarmen I'm going to close this out for now. If you're still having the problem after running `pod repo update`, please let me know and we can reopen and investigate further!

**Comment by YoungCarmen** [comment]
thanks very much 
The problem was solved while i executed the pod repo update action

**Comment by Govinda13** [comment]
It didn't work for me. I am still getting same error. Any other solution for this?

**Comment by stephencelis** [comment]
@Govinda13 We no longer support CocoaPods, though the existing spec is still there: https://cocoapods.org/pods/PointFree-Validated

We'd recommend using SPM these days.
